In [1]:
    import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model= Sequential()

model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\ADISH\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 0.11262369, -0.2737016 ],
        [-0.831663  , -0.560263  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.326389],
        [1.102883]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights= [np.array([[ 0.1 , 0.1],
        [0.1 , 0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1 ],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [9]:
optimizer= keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [10]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 503.2255 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 478.5388 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 463.2706
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 493.8261 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 555.0596
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 552.2289
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 475.3021
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 539.3196
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 410.2751
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 439.3692
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 391.5524 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 456.4944 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 376.1030 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 420.5830 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 381.3565 
Epo

In [11]:
model.get_weights()

[array([[ 0.35792384, -0.03102856],
        [-0.5957141 , -0.3268075 ]], dtype=float32),
 array([0.24326786, 0.24068171], dtype=float32),
 array([[1.1235313 ],
        [0.89536214]], dtype=float32),
 array([0.25350696], dtype=float32)]